<Type Name="MsalException" FullName="Microsoft.Identity.Client.MsalException">
  <TypeSignature Language="C#" Value="public class MsalException : Exception" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit MsalException extends System.Exception" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Identity.Client.MsalException" />
  <TypeSignature Language="VB.NET" Value="Public Class MsalException&#xA;Inherits Exception" />
  <TypeSignature Language="F#" Value="type MsalException = class&#xA;    inherit Exception" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Identity.Client</AssemblyName>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
            <span data-ttu-id="c1acd-101">トークンの取得中にエラーが発生したときにスローされる例外の種類。</span><span class="sxs-lookup"><span data-stu-id="c1acd-101">The exception type thrown when an error occurs during token acquisition.</span></span>
            </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalException.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
            <span data-ttu-id="c1acd-102">Exception クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="c1acd-102">Initializes a new instance of the exception class.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalException (string errorCode);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalException.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String)" />
      <MemberSignature Language="F#" Value="new Microsoft.Identity.Client.MsalException : string -&gt; Microsoft.Identity.Client.MsalException" Usage="new Microsoft.Identity.Client.MsalException errorCode" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="errorCode">
            <span data-ttu-id="c1acd-103">エラー コードでは、サービスによって返されるか、クライアントによって生成されます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-103">The error code returned by the service or generated by client.</span></span> <span data-ttu-id="c1acd-104">これは、コードの例外を処理するために依存することができます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-104">This is the code you can rely on for exception handling.</span></span>
            </param>
        <summary>
            <span data-ttu-id="c1acd-105">指定されたエラー コードで例外クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="c1acd-105">Initializes a new instance of the exception class with a specified error code.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalException (string errorCode, string errorMessage);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode, string errorMessage) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalException.#ctor(System.String,System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String, errorMessage As String)" />
      <MemberSignature Language="F#" Value="new Microsoft.Identity.Client.MsalException : string * string -&gt; Microsoft.Identity.Client.MsalException" Usage="new Microsoft.Identity.Client.MsalException (errorCode, errorMessage)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
        <Parameter Name="errorMessage" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="errorCode">
            <span data-ttu-id="c1acd-106">エラー コードでは、サービスによって返されるか、クライアントによって生成されます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-106">The error code returned by the service or generated by client.</span></span> <span data-ttu-id="c1acd-107">これは、コードの例外を処理するために依存することができます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-107">This is the code you can rely on for exception handling.</span></span>
            </param>
        <param name="errorMessage"><span data-ttu-id="c1acd-108">例外の原因を説明するエラー メッセージ。</span><span class="sxs-lookup"><span data-stu-id="c1acd-108">The error message that explains the reason for the exception.</span></span></param>
        <summary>
            <span data-ttu-id="c1acd-109">指定されたエラー コードとエラー メッセージ、例外クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="c1acd-109">Initializes a new instance of the exception class with a specified error code and error message.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public MsalException (string errorCode, string errorMessage, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode, string errorMessage, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalException.#ctor(System.String,System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String, errorMessage As String, innerException As Exception)" />
      <MemberSignature Language="F#" Value="new Microsoft.Identity.Client.MsalException : string * string * Exception -&gt; Microsoft.Identity.Client.MsalException" Usage="new Microsoft.Identity.Client.MsalException (errorCode, errorMessage, innerException)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
        <Parameter Name="errorMessage" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="errorCode">
            <span data-ttu-id="c1acd-110">エラー コードでは、サービスによって返されるか、クライアントによって生成されます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-110">The error code returned by the service or generated by client.</span></span> <span data-ttu-id="c1acd-111">これは、コードの例外を処理するために依存することができます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-111">This is the code you can rely on for exception handling.</span></span>
            </param>
        <param name="errorMessage"><span data-ttu-id="c1acd-112">例外の原因を説明するエラー メッセージ。</span><span class="sxs-lookup"><span data-stu-id="c1acd-112">The error message that explains the reason for the exception.</span></span></param>
        <param name="innerException">
            <span data-ttu-id="c1acd-113">内部例外が指定されていない場合、現在の例外または null 参照の原因となった例外。</span><span class="sxs-lookup"><span data-stu-id="c1acd-113">The exception that is the cause of the current exception, or a null reference if no inner exception is specified.</span></span>
            </param>
        <summary>
            <span data-ttu-id="c1acd-114">指定されたエラー コードとは、この例外の原因となった内部例外への参照を伴う exception クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="c1acd-114">Initializes a new instance of the exception class with a specified error code and a reference to the inner exception that is the cause of this exception.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="ErrorCode">
      <MemberSignature Language="C#" Value="public string ErrorCode { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string ErrorCode" />
      <MemberSignature Language="DocId" Value="P:Microsoft.Identity.Client.MsalException.ErrorCode" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property ErrorCode As String" />
      <MemberSignature Language="F#" Value="member this.ErrorCode : string" Usage="Microsoft.Identity.Client.MsalException.ErrorCode" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="c1acd-115">サービスによって返されるか、クライアントによって生成されたプロトコル エラー コードを取得します。</span><span class="sxs-lookup"><span data-stu-id="c1acd-115">Gets the protocol error code returned by the service or generated by client.</span></span> <span data-ttu-id="c1acd-116">これは、コードの例外を処理するために依存することができます。</span><span class="sxs-lookup"><span data-stu-id="c1acd-116">This is the code you can rely on for exception handling.</span></span>
            </summary>
        <value>To be added.</value>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="ToString">
      <MemberSignature Language="C#" Value="public override string ToString ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig virtual instance string ToString() cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Identity.Client.MsalException.ToString" />
      <MemberSignature Language="VB.NET" Value="Public Overrides Function ToString () As String" />
      <MemberSignature Language="F#" Value="override this.ToString : unit -&gt; string" Usage="msalException.ToString " />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>
            <span data-ttu-id="c1acd-117">現在の例外の文字列形式を作成して返します。</span><span class="sxs-lookup"><span data-stu-id="c1acd-117">Creates and returns a string representation of the current exception.</span></span>
            </summary>
        <returns><span data-ttu-id="c1acd-118">現在の例外の文字列形式。</span><span class="sxs-lookup"><span data-stu-id="c1acd-118">A string representation of the current exception.</span></span></returns>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="UnknownError">
      <MemberSignature Language="C#" Value="public const string UnknownError;" />
      <MemberSignature Language="ILAsm" Value=".field public static literal string UnknownError" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Identity.Client.MsalException.UnknownError" />
      <MemberSignature Language="VB.NET" Value="Public Const UnknownError As String " />
      <MemberSignature Language="F#" Value="val mutable UnknownError : string" Usage="Microsoft.Identity.Client.MsalException.UnknownError" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Identity.Client</AssemblyName>
        <AssemblyVersion>1.1.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="c1acd-119">不明なエラーが発生しました。</span><span class="sxs-lookup"><span data-stu-id="c1acd-119">Unknown Error occured.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>