<Type Name="IFileStagingArtifact" FullName="Microsoft.Azure.Batch.IFileStagingArtifact">
  <TypeSignature Language="C#" Value="public interface IFileStagingArtifact" />
  <TypeSignature Language="ILAsm" Value=".class public interface auto ansi abstract IFileStagingArtifact" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Azure.Batch.IFileStagingArtifact" />
  <TypeSignature Language="VB.NET" Value="Public Interface IFileStagingArtifact" />
  <TypeSignature Language="F#" Value="type IFileStagingArtifact = interface" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Azure.Batch</AssemblyName>
    <AssemblyVersion>7.1.0.0</AssemblyVersion>
    <AssemblyVersion>8.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Interfaces />
  <Docs>
    <summary>
            <span data-ttu-id="f2ba7-101">ステージング処理ファイルに関する情報が含まれています。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-101">Contains information about a file staging process.</span></span>  <span data-ttu-id="f2ba7-102">ファイル ステージングは、通常の実行、 <see cref="T:Microsoft.Azure.Batch.CloudTask" /> (を参照してください<see cref="P:Microsoft.Azure.Batch.CloudTask.FilesToStage" />)。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-102">File staging is typically performed for a <see cref="T:Microsoft.Azure.Batch.CloudTask" /> (see <see cref="P:Microsoft.Azure.Batch.CloudTask.FilesToStage" />).</span></span>
            </summary>
    <remarks>
      <para>
            <span data-ttu-id="f2ba7-103">IFileStagingArtifact により、アプリケーションをカスタマイズして、ファイルをアップロード、クラウドでは、たとえば、タスク関連の操作の一部としてなど、プロセスに関する情報を取得する<see cref="M:Microsoft.Azure.Batch.JobOperations.AddTaskAsync(System.String,System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.CloudTask},Microsoft.Azure.Batch.BatchClientParallelOptions,System.Collections.Concurrent.ConcurrentBag{System.Collections.Concurrent.ConcurrentDictionary{System.Type,Microsoft.Azure.Batch.IFileStagingArtifact}},System.Nullable{System.TimeSpan},System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.BatchClientBehavior})">JobOperations.AddTaskAsync</see>または<see cref="M:Microsoft.Azure.Batch.CloudJob.AddTaskAsync(Microsoft.Azure.Batch.CloudTask,System.Collections.Concurrent.ConcurrentDictionary{System.Type,Microsoft.Azure.Batch.IFileStagingArtifact},System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.BatchClientBehavior},System.Threading.CancellationToken)">CloudJob.AddTaskAsync</see>です。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-103">IFileStagingArtifact allows an application to customize and to obtain information about the process of uploading files to the cloud, for example as part of a task-related operation such as <see cref="M:Microsoft.Azure.Batch.JobOperations.AddTaskAsync(System.String,System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.CloudTask},Microsoft.Azure.Batch.BatchClientParallelOptions,System.Collections.Concurrent.ConcurrentBag{System.Collections.Concurrent.ConcurrentDictionary{System.Type,Microsoft.Azure.Batch.IFileStagingArtifact}},System.Nullable{System.TimeSpan},System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.BatchClientBehavior})">JobOperations.AddTaskAsync</see> or <see cref="M:Microsoft.Azure.Batch.CloudJob.AddTaskAsync(Microsoft.Azure.Batch.CloudTask,System.Collections.Concurrent.ConcurrentDictionary{System.Type,Microsoft.Azure.Batch.IFileStagingArtifact},System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.BatchClientBehavior},System.Threading.CancellationToken)">CloudJob.AddTaskAsync</see>.</span></span>  <span data-ttu-id="f2ba7-104">アプリケーションは、この情報を使用して、たとえば、Azure ストレージにアップロード プロセスの一部として作成されたコンテナーが情報を入手することがあります。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-104">Applications may use this information to, for example, find out about containers that were created in Azure Storage as part of the upload process.</span></span>
            </para>
      <para>
            <span data-ttu-id="f2ba7-105">ときに<see cref="M:Microsoft.Azure.Batch.JobOperations.AddTaskAsync(System.String,System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.CloudTask},Microsoft.Azure.Batch.BatchClientParallelOptions,System.Collections.Concurrent.ConcurrentBag{System.Collections.Concurrent.ConcurrentDictionary{System.Type,Microsoft.Azure.Batch.IFileStagingArtifact}},System.Nullable{System.TimeSpan},System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.BatchClientBehavior})">JobOperations.AddTaskAsync</see>が呼び出されると、コレクションのサービスのバッチに作業バッチのクライアントが送信されます。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-105">When <see cref="M:Microsoft.Azure.Batch.JobOperations.AddTaskAsync(System.String,System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.CloudTask},Microsoft.Azure.Batch.BatchClientParallelOptions,System.Collections.Concurrent.ConcurrentBag{System.Collections.Concurrent.ConcurrentDictionary{System.Type,Microsoft.Azure.Batch.IFileStagingArtifact}},System.Nullable{System.TimeSpan},System.Collections.Generic.IEnumerable{Microsoft.Azure.Batch.BatchClientBehavior})">JobOperations.AddTaskAsync</see> is called, the Batch client sends the tasks to the Batch service in collections.</span></span>  <span data-ttu-id="f2ba7-106">バッチ クライアントがそのコレクションに対してファイルのステージングを実行する各コレクションを処理すると、: いずれかを指定ようなかどうかに表示するタスクを調べます<see cref="P:Microsoft.Azure.Batch.CloudTask.FilesToStage" />、され、その場合、ディクショナリ エントリの種類ごとに<see cref="T:Microsoft.Azure.Batch.FileStaging.IFileStagingProvider" />FilesToStage コレクション。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-106">As each collection is processed, the Batch client performs file staging for that collection: it examines the tasks to see if any of them specify any <see cref="P:Microsoft.Azure.Batch.CloudTask.FilesToStage" />, and if so creates a dictionary entry for each type of <see cref="T:Microsoft.Azure.Batch.FileStaging.IFileStagingProvider" /> in the FilesToStage collection.</span></span> <span data-ttu-id="f2ba7-107">ディクショナリ エントリのキーは、<see cref="T:System.Type" />値と、IFileStagingProvider は IFileStagingArtifact の対応する実装のインスタンス。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-107">The key of the dictionary entry is the <see cref="T:System.Type" /> of the IFileStagingProvider and the value is an instance of the corresponding implementation of IFileStagingArtifact.</span></span>  <span data-ttu-id="f2ba7-108">たとえば、FilesToStage には、1 つ以上の FileToStage オブジェクト (Microsoft.Azure.Batch.FileStaging ライブラリから) が含まれている場合、ディクショナリに含まれるキーを持つ typeof(FileToStage) は、その値のインスタンスのエントリSequentialFileStagingArtifact です。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-108">For example, if FilesToStage includes one or more FileToStage objects (from the Microsoft.Azure.Batch.FileStaging library), then the dictionary contains an entry whose key is typeof(FileToStage) and whose value is an instance of SequentialFileStagingArtifact.</span></span>
            </para>
      <para>
            <span data-ttu-id="f2ba7-109">タスクの追加操作が完了したら、またはアプリケーションがマルチ スレッドの場合、タスクの追加操作中に、ディクショナリを確認し、各 IFileStagingArtifact を型固有の情報を取得する適切な型に変換できます。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-109">When the Add Task operation completes, or during the Add Task operation if the application is multi-threaded, you can examine the dictionary and convert each IFileStagingArtifact to the appropriate type to retrieve the type-specific information.</span></span>  <span data-ttu-id="f2ba7-110">たとえば、タスクの追加操作には、1 つまたは複数の FileToStage オブジェクトが指定されている場合、typeof(FileToStage) によってキー指定された辞書エントリが見つかりません、SequentialFileStagingArtifact に値をキャストして調査できます、SequentialFileStagingArtifact.BlobContainerCreated プロパティのアップロード プロセスは、Azure ストレージに blob コンテナーを作成し、その場合はそのコンテナーの名前。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-110">For example, if your Add Task operation specified one or more FileToStage objects, you can locate the dictionary entry keyed by typeof(FileToStage), cast the value to SequentialFileStagingArtifact, and examine the SequentialFileStagingArtifact.BlobContainerCreated property to determine if the upload process created a blob container in Azure Storage and if so the name of that container.</span></span>
            <span data-ttu-id="f2ba7-111">この例は、自動的に作成されたコンテナーのクリーンアップに役立つ可能性があります。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-111">This example could be useful for cleaning up automatically created containers.</span></span>
            </para>
      <para>
            <span data-ttu-id="f2ba7-112">(単一タスクの追加のタスクの操作でも同様、点を除いて、複数のタスクのタスクの追加操作で、各タスクのコレクションの辞書がおよびで収集されます辞書、<see cref="T:System.Collections.Concurrent.ConcurrentBag`1" />単一タスクのタスクの追加操作であるだけに対して、。1 つのディクショナリ)。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-112">(Single-task Add Task operations work similarly, except that in a multi-task Add Task operation, there is a dictionary for each collection of tasks, and the dictionaries are collected in a <see cref="T:System.Collections.Concurrent.ConcurrentBag`1" />, whereas in a single-task Add Task operation there is only a single dictionary.)</span></span>
            </para>
      <para>
            <span data-ttu-id="f2ba7-113">単一タスクのタスクの追加操作でファイルを事前設定することで適切なエントリでステージング処理をカスタマイズするのにディクショナリを使用することもできます。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-113">In a single-task Add Task operation, you can also use the dictionary to customize the file staging process, by pre-populating it with appropriate entries.</span></span>  <span data-ttu-id="f2ba7-114">たとえば、制御する、 <see cref="P:Microsoft.Azure.Batch.IFileStagingArtifact.NamingFragment" /> FileToStage オブジェクトのグループにします。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-114">For example, suppose you wish to control the <see cref="P:Microsoft.Azure.Batch.IFileStagingArtifact.NamingFragment" /> for a group of FileToStage objects.</span></span>  <span data-ttu-id="f2ba7-115">使用してディクショナリを初期化できますし、 <c>{typeof(FileToStage)、新しい SequentialFileStagingArtifact {NamingFragment ="myname"}}</c> AddTaskAsync に渡す前にします。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-115">Then you could initialize the dictionary with <c>{ typeof(FileToStage), new SequentialFileStagingArtifact { NamingFragment = "myname" } }</c> before passing it to AddTaskAsync.</span></span>  <span data-ttu-id="f2ba7-116">IFileStagingProvider の FileToStage 実装には、独自に作成する代わりに、SequentialFileStagingArtifact し、使用します。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-116">The FileToStage implementation of IFileStagingProvider would then use your SequentialFileStagingArtifact instead of creating its own.</span></span>  <span data-ttu-id="f2ba7-117">(この機能は複数のタスクのタスクの追加操作で使用できません) です。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-117">(This feature is not available in multi-task Add Task operations.)</span></span>
            </para>
      <para>
            <span data-ttu-id="f2ba7-118">カスタムを開発している場合にも IFileStagingArtifact が発生する可能性があります<see cref="T:Microsoft.Azure.Batch.FileStaging.IFileStagingProvider" />です。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-118">You may also encounter IFileStagingArtifact if you are developing a custom <see cref="T:Microsoft.Azure.Batch.FileStaging.IFileStagingProvider" />.</span></span>
            <span data-ttu-id="f2ba7-119">ここでは実装に固有の情報を報告する IFileStagingArtifact のカスタム実装には、ステージング処理は、ファイルは通常作成します。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-119">In this case you will typically create a custom implementation of IFileStagingArtifact to report implementation-specific information about your file staging process.</span></span>
            </para>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="NamingFragment">
      <MemberSignature Language="C#" Value="public string NamingFragment { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string NamingFragment" />
      <MemberSignature Language="DocId" Value="P:Microsoft.Azure.Batch.IFileStagingArtifact.NamingFragment" />
      <MemberSignature Language="VB.NET" Value="Public Property NamingFragment As String" />
      <MemberSignature Language="F#" Value="member this.NamingFragment : string with get, set" Usage="Microsoft.Azure.Batch.IFileStagingArtifact.NamingFragment" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Azure.Batch</AssemblyName>
        <AssemblyVersion>7.1.0.0</AssemblyVersion>
        <AssemblyVersion>8.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="f2ba7-120">取得または既定の名前を構築するときに使用できる名前フラグメントを設定します。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-120">Gets or sets a name fragment that can be used when constructing default names.</span></span>
            </summary>
        <value>To be added.</value>
        <remarks><span data-ttu-id="f2ba7-121">呼び出し元は、このプロパティを設定可能性がありますが、<see cref="T:Microsoft.Azure.Batch.FileStaging.IFileStagingProvider" />実装は、これを考慮する必要はありません。</span><span class="sxs-lookup"><span data-stu-id="f2ba7-121">Although a caller may set this property, the <see cref="T:Microsoft.Azure.Batch.FileStaging.IFileStagingProvider" /> implementation is not required to respect it.</span></span></remarks>
      </Docs>
    </Member>
  </Members>
</Type>