<Type Name="IndexAnalyzerAttribute" FullName="Microsoft.Azure.Search.IndexAnalyzerAttribute">
  <TypeSignature Language="C#" Value="public class IndexAnalyzerAttribute : Attribute" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit IndexAnalyzerAttribute extends System.Attribute" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Azure.Search.IndexAnalyzerAttribute" />
  <TypeSignature Language="VB.NET" Value="Public Class IndexAnalyzerAttribute&#xA;Inherits Attribute" />
  <TypeSignature Language="F#" Value="type IndexAnalyzerAttribute = class&#xA;    inherit Attribute" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Azure.Search</AssemblyName>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Attribute</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.AttributeUsage(System.AttributeTargets.Property)</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
            <span data-ttu-id="8e21b-101">示します、<see cref="T:Microsoft.Azure.Search.Models.Field" />によって生成された<see cref="T:Microsoft.Azure.Search.FieldBuilder" />ターゲットのプロパティが含まれて、<see cref="P:Microsoft.Azure.Search.Models.Field.IndexAnalyzer" />プロパティを指定されたアナライザーに設定します。</span><span class="sxs-lookup"><span data-stu-id="8e21b-101">Indicates that the <see cref="T:Microsoft.Azure.Search.Models.Field" /> generated by <see cref="T:Microsoft.Azure.Search.FieldBuilder" /> for the target property should have its <see cref="P:Microsoft.Azure.Search.Models.Field.IndexAnalyzer" /> property set to the specified analyzer.</span></span>
            </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public IndexAnalyzerAttribute (string analyzerName);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string analyzerName) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.Azure.Search.IndexAnalyzerAttribute.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (analyzerName As String)" />
      <MemberSignature Language="F#" Value="new Microsoft.Azure.Search.IndexAnalyzerAttribute : string -&gt; Microsoft.Azure.Search.IndexAnalyzerAttribute" Usage="new Microsoft.Azure.Search.IndexAnalyzerAttribute analyzerName" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Azure.Search</AssemblyName>
        <AssemblyVersion>3.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="analyzerName" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="analyzerName">
            <span data-ttu-id="8e21b-102">アナライザーの名前です。</span><span class="sxs-lookup"><span data-stu-id="8e21b-102">The name of the analyzer.</span></span> <span data-ttu-id="8e21b-103">内の名前のいずれかを使用して<see cref="T:Microsoft.Azure.Search.Models.AnalyzerName.AsString" />またはカスタム アナライザーの名前。</span><span class="sxs-lookup"><span data-stu-id="8e21b-103">Use one of the names in <see cref="T:Microsoft.Azure.Search.Models.AnalyzerName.AsString" /> or the name of a custom analyzer.</span></span>
            </param>
        <summary>
            <span data-ttu-id="8e21b-104">指定されたアナライザーを使用することを示します。</span><span class="sxs-lookup"><span data-stu-id="8e21b-104">Indicates that the specified analyzer should be used.</span></span>
            </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="Name">
      <MemberSignature Language="C#" Value="public string Name { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string Name" />
      <MemberSignature Language="DocId" Value="P:Microsoft.Azure.Search.IndexAnalyzerAttribute.Name" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Name As String" />
      <MemberSignature Language="F#" Value="member this.Name : string" Usage="Microsoft.Azure.Search.IndexAnalyzerAttribute.Name" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Azure.Search</AssemblyName>
        <AssemblyVersion>3.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>To be added.</summary>
        <value>To be added.</value>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>