<Type Name="AdalServiceException" FullName="Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException">
  <TypeSignature Language="C#" Value="public class AdalServiceException : Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit AdalServiceException extends Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException" />
  <TypeSignature Language="DocId" Value="T:Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException" />
  <TypeSignature Language="VB.NET" Value="Public Class AdalServiceException&#xA;Inherits AdalException" />
  <TypeSignature Language="F#" Value="type AdalServiceException = class&#xA;    inherit AdalException" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.IdentityModel.Clients.ActiveDirectory</AssemblyName>
    <AssemblyVersion>3.16.0.14</AssemblyVersion>
    <AssemblyVersion>3.17.3.35304</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
            <span data-ttu-id="7f17d-101">ユーザーがサービスによって返されるときにスローされる例外の種類では、要求内のユーザーが一致しません。</span><span class="sxs-lookup"><span data-stu-id="7f17d-101">The exception type thrown when user returned by service does not match user in the request.</span></span>
            </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AdalServiceException (string errorCode, string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string errorCode, string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.#ctor(System.String,System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (errorCode As String, message As String)" />
      <MemberSignature Language="F#" Value="new Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException : string * string -&gt; Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException" Usage="new Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException (errorCode, message)" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.IdentityModel.Clients.ActiveDirectory</AssemblyName>
        <AssemblyVersion>3.16.0.14</AssemblyVersion>
        <AssemblyVersion>3.17.3.35304</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="errorCode" Type="System.String" />
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="errorCode"><span data-ttu-id="7f17d-102">プロトコル エラー コードでは、サービスによって返されるか、クライアントによって生成されます。</span><span class="sxs-lookup"><span data-stu-id="7f17d-102">The protocol error code returned by the service or generated by client.</span></span> <span data-ttu-id="7f17d-103">これは、コードの例外を処理するために依存することができます。</span><span class="sxs-lookup"><span data-stu-id="7f17d-103">This is the code you can rely on for exception handling.</span></span></param>
        <param name="message"><span data-ttu-id="7f17d-104">例外の原因を説明するエラー メッセージ。</span><span class="sxs-lookup"><span data-stu-id="7f17d-104">The error message that explains the reason for the exception.</span></span></param>
        <summary>
             <span data-ttu-id="7f17d-105">指定されたエラー コードとエラー メッセージ、例外クラスの新しいインスタンスを初期化します。</span><span class="sxs-lookup"><span data-stu-id="7f17d-105">Initializes a new instance of the exception class with a specified error code and error message.</span></span>
             </summary>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="Headers">
      <MemberSignature Language="C#" Value="public System.Net.Http.Headers.HttpResponseHeaders Headers { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Net.Http.Headers.HttpResponseHeaders Headers" />
      <MemberSignature Language="DocId" Value="P:Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.Headers" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Headers As HttpResponseHeaders" />
      <MemberSignature Language="F#" Value="member this.Headers : System.Net.Http.Headers.HttpResponseHeaders" Usage="Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.Headers" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.IdentityModel.Clients.ActiveDirectory</AssemblyName>
        <AssemblyVersion>3.17.3.35304</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Net.Http.Headers.HttpResponseHeaders</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="7f17d-106">エラーを示す応答からヘッダーが含まれています</span><span class="sxs-lookup"><span data-stu-id="7f17d-106">Contains headers from the response that indicated an error</span></span>
            </summary>
        <value>To be added.</value>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="ServiceErrorCodes">
      <MemberSignature Language="C#" Value="public string[] ServiceErrorCodes { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string[] ServiceErrorCodes" />
      <MemberSignature Language="DocId" Value="P:Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.ServiceErrorCodes" />
      <MemberSignature Language="VB.NET" Value="Public Property ServiceErrorCodes As String()" />
      <MemberSignature Language="F#" Value="member this.ServiceErrorCodes : string[] with get, set" Usage="Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.ServiceErrorCodes" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.IdentityModel.Clients.ActiveDirectory</AssemblyName>
        <AssemblyVersion>3.16.0.14</AssemblyVersion>
        <AssemblyVersion>3.17.3.35304</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String[]</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="7f17d-107">サービスによって返される可能性がある特定のエラー コードを取得します。</span><span class="sxs-lookup"><span data-stu-id="7f17d-107">Gets the specific error codes that may be returned by the service.</span></span>
            </summary>
        <value>To be added.</value>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="StatusCode">
      <MemberSignature Language="C#" Value="public int StatusCode { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance int32 StatusCode" />
      <MemberSignature Language="DocId" Value="P:Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.StatusCode" />
      <MemberSignature Language="VB.NET" Value="Public Property StatusCode As Integer" />
      <MemberSignature Language="F#" Value="member this.StatusCode : int with get, set" Usage="Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.StatusCode" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.IdentityModel.Clients.ActiveDirectory</AssemblyName>
        <AssemblyVersion>3.16.0.14</AssemblyVersion>
        <AssemblyVersion>3.17.3.35304</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Int32</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
            <span data-ttu-id="7f17d-108">Http 層から返されたステータス コードを取得します。</span><span class="sxs-lookup"><span data-stu-id="7f17d-108">Gets the status code returned from http layer.</span></span> <span data-ttu-id="7f17d-109">この状態コードは内部 HttpRequestException 応答で、いずれかの HttpStatusCode またはブラウザーで NavigateError イベントのステータス コード ベースのフロー (を参照してください http://msdn.microsoft.com/en-us/library/bb268233 (v=vs.85).aspx)。</span><span class="sxs-lookup"><span data-stu-id="7f17d-109">This status code is either the HttpStatusCode in the inner HttpRequestException response or NavigateError Event Status Code in browser based flow (See http://msdn.microsoft.com/en-us/library/bb268233(v=vs.85).aspx).</span></span>
            <span data-ttu-id="7f17d-110">再試行ロジックやエラーの調査を実装するなどの目的は、このコードを使用することができます。</span><span class="sxs-lookup"><span data-stu-id="7f17d-110">You can use this code for purposes such as implementing retry logic or error investigation.</span></span>
            </summary>
        <value>To be added.</value>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
    <Member MemberName="ToString">
      <MemberSignature Language="C#" Value="public override string ToString ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig virtual instance string ToString() cil managed" />
      <MemberSignature Language="DocId" Value="M:Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException.ToString" />
      <MemberSignature Language="VB.NET" Value="Public Overrides Function ToString () As String" />
      <MemberSignature Language="F#" Value="override this.ToString : unit -&gt; string" Usage="adalServiceException.ToString " />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.IdentityModel.Clients.ActiveDirectory</AssemblyName>
        <AssemblyVersion>3.16.0.14</AssemblyVersion>
        <AssemblyVersion>3.17.3.35304</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>
            <span data-ttu-id="7f17d-111">現在の例外の文字列形式を作成して返します。</span><span class="sxs-lookup"><span data-stu-id="7f17d-111">Creates and returns a string representation of the current exception.</span></span>
            </summary>
        <returns><span data-ttu-id="7f17d-112">現在の例外の文字列形式。</span><span class="sxs-lookup"><span data-stu-id="7f17d-112">A string representation of the current exception.</span></span></returns>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
  </Members>
</Type>